# plotting Figure 8 using MCMC estimates
# users must use data files generated by GrowMbf2000.R, GrowM06_18MPauly.R, and GrowM06_18MtoK.R
# these files are too large to upload.
# A similar figure can be plotted using plot_Mpriorpostnormdis.R
setwd("E:/fishr/cardinalisM")
rm(list=ls())
databf00<-read.csv("M_bf2000_mcmc.csv")
data6<-read.csv("M_2006_mcmc.csv")
data7<-read.csv("M_2007_mcmc.csv")
data8<-read.csv("M_2008_mcmc.csv")
data14<-read.csv("M_2014_mcmc.csv")
data18<-read.csv("M_2018_mcmc.csv")

datar6<-read.csv("M2_2006_mcmc.csv")
datar7<-read.csv("M2_2007_mcmc.csv")
datar8<-read.csv("M2_2008_mcmc.csv")
datar14<-read.csv("M2_2014_mcmc.csv")
datar18<-read.csv("M2_2018_mcmc.csv")

den_bf00<-density(databf00$'theta.3.')   
den_6<-density(data6$'theta.3.')
den_7<-density(data7$'theta.3.')
den_8<-density(data8$'theta.3.')
den_14<-density(data14$'theta.3.')
den_18<-density(data18$'theta.3.')

den_r6<-density(datar6$'theta.3.')
den_r7<-density(datar7$'theta.3.')
den_r8<-density(datar8$'theta.3.')
den_r14<-density(datar14$'theta.3.')
den_r18<-density(datar18$'theta.3.')
   
#prior
M<-seq(0,1.3,0.01); den_p<-dgamma(M,4.1878,9.5290);

pdf("Mpriorpost.pdf",width = 15/2.54, height = 12.4/2.54 )
layout(matrix(c(1,2,3,3),byrow=TRUE,ncol=2)) 
par(oma=c(0,0,0,0),mar=c(4,4,0.5,1),cex=0.8,las=1,mgp=c(2.5,1,0))

plot(M,den_p,type="l",lty=3,main="",col="black",tck=-0.03,
     xlim=c(0,1.4),  ylim=c(0,6.5),
      xlab=bquote(italic(M)~(year^{-1})),ylab="Density") #solid 
lines(den_bf00$x[den_bf00$x>=0&den_bf00$x<=1.4],den_bf00$y[den_bf00$x>=0&den_bf00$x<=1.4],lty=2)
lines(den_6$x[den_6$x>=0&den_6$x<=1.4],den_6$y[den_6$x>=0&den_6$x<=1.4],lty=2,col="blue")#2006
lines(den_7$x,den_7$y,lty=4,col="green")#2007
lines(den_8$x,den_8$y,lty=5,col="magenta")#2008
lines(den_14$x,den_14$y,lty=6,col="cyan")#2014
lines(den_18$x,den_18$y,lty=1,col="red")#2018
  
plot(M,den_p,type="l",lty=3,main="",col="black",tck=-0.03,
      xlim=c(0,1.4), ylim=c(0,6.5),
      xlab=bquote(italic(M)~(year^{-1})),ylab="Density") #solid 
lines(den_bf00$x[den_bf00$x>=0&den_bf00$x<=1.4],den_bf00$y[den_bf00$x>=0&den_bf00$x<=1.4],lty=2)
lines(den_r6$x[den_r6$x>=0&den_6$x<=1.4],den_r6$y[den_r6$x>=0&den_6$x<=1.4],lty=2,col="blue")#2006
lines(den_r7$x[den_r7$x>=0&den_6$x<=1.4],den_r7$y[den_r7$x>=0&den_6$x<=1.4],lty=4,col="green")#2007
lines(den_r8$x,den_r8$y,lty=5,col="magenta")#2008
lines(den_r14$x,den_r14$y,lty=6,col="cyan")#2014
lines(den_r18$x,den_r18$y,lty=1,col="red")#2018         

plot(0,0, type="n", axes=FALSE,bty="n",xlab="",ylab="")
legend("top",c("Prior", "1999","2006","2007","2008","2014","2018"),lty=c(3,2,2,4,5,6,1),
       col=c("black","black","blue","green","magenta","cyan","red"), bty="n",horiz=TRUE)

dev.off()
